# action.yml
name: 'MongoDB Atlas Resume'
description: 'Resume a MongoDB Atlas Cluster'
branding:
  icon: play
  color: green
inputs:
  public_api_key:
    description: 'MongoDB Atlas Public API Key'
    required: true
  private_api_key:
    description: 'MongoDB Atlas Private API Key'
    required: true
  project_id:
    description: 'MongoDB Atlas Project ID'
    required: true
  cluster_name:
    description: 'MongoDB Atlas Cluster Name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.public_api_key }}
    - ${{ inputs.private_api_key }}
    - ${{ inputs.project_id }}
    - ${{ inputs.cluster_name }}
